name: Build RTSan Libs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Download and Extract
      run: make init

    - name: Configure
      run: make configure

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Upload artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu_rtsan
        path: ./llvm-project/build/lib/linux/libclang_rt.rtsan-*.a
        retention-days: 1
